set runtimepath+=~/.vim_runtime

" system-wide vimrc if present
try
    source /etc/vimrc
catch
endtry

" Use Amix's vimrc
source ~/.vim_runtime/vimrcs/basic.vim
source ~/.vim_runtime/vimrcs/filetypes.vim
"source ~/.vim_runtime/vimrcs/plugins_config.vim
"source ~/.vim_runtime/vimrcs/extended.vim


" own stuff
try
    source ~/.dotfiles/vim/my_configs.vim
catch
endtry

colorscheme default
